### ISSUE TITLE
Exact Title matching in get_pubmed_ids_by_fulltitle()

### ISSUE THREAD

**Issue by padpadpadpad** [dami82/easyPubMed#17]
Hi @dami82 

Neat package! Just wondering if there is a way to get exact Title matching using get_pubmed_ids_by_fulltitle().

For example, when I have a title of:

```r
x = 'Micrococcus luteus endocarditis: case report and review of the literature.'
y = get_pubmed_ids_by_fulltitle(x, field = '[Title]')

y$Count
y$IdList
```

There are three hits, even though there is only one with the exact title name. Is there any way to be more specific? Or filtering out for the real match.

Cheers
Dan

**Comment by dami82** [comment]
Hi Dan, 

Thanks for this question.
I performed a similar search using the PubMed website, and I also got: `3 articles found by citation matching`.
From my perspective, that is a great result, since it means that the `easyPubMed` library behaves as expected. While this may sound counterintuitive, I am striving to match the website behavior rather than finding the perfect match in this situation. 

If you know which is the article you want, I would strongly recommend to proceed by querying by PMID rather than by fulltitle. Your query string should look like:  `query_string = "34097668[PMID]"`.
I hope this is useful.
