### ISSUE TITLE
Incorrect publication year from PMID query (article_to_df)

### ISSUE THREAD

**Issue by taywll252** [dami82/easyPubMed#6]
I was performing queries to compile article data based on PMID, I tried to search for the following article, but the returned publication year doesn't match the PubMed website.

**Example PubMed link:** https://pubmed.ncbi.nlm.nih.gov/23344044/
**Expected Publication Year:** 2013
**Returned Publication Year:** 2015

**Example Code:**

library(dplyr); library(easyPubMed)
get_pubmed_ids(23344044) %>% 
fetch_pubmed_data() %>% 
article_to_df(getAuthors = FALSE) %>% 
select(year)

R version 4.0.0 (2020-04-24) Arbor Day

**Comment by dami82** [comment]
I cannot reproduce this issue. Your code returns "2013" as expected.
Are you using an old version of the library?
Please, make sure you are using _easyPubMed_ version 2.21.

**Comment by taywll252** [comment]
Thanks for the quick response. I was using the version 2.13 available from CRAN (install.packages("easyPubMed")). But yes, downloading the dev version 2.21 directly from GitHub produced the correct output.

**Comment by dami82** [comment]
Glad to hear this. I am planning to update the CRAN version of easyPubMed by the end of the year (or early next year). Version 2.13 and 2.15 had an issue where "completed date" was retrieved instead of "published date". I think this drove the issue you experienced. Again, thanks for using the library. :-)
