### ISSUE TITLE
articles_to_list only listing 5000 articles

### ISSUE THREAD

**Issue by dwill023** [dami82/easyPubMed#9]
Hi, I ran the below R code:

```
# fetch all data
batches = batch_pubmed_download(pubmed_query_string = 'MicroRNAs[MeSH]',
                                dest_file_prefix = "mirnas_pubmed_",
                                batch_size = 10000)

listed_articles2 <- articles_to_list(pubmed_data = batches[2], simplify = F)
```

and it produced xml text files for 10,000 PubmedArticle per file but when I try to list out the articles using the function articles_to_list() I am only getting 5000 in the list. Is there something I'm missing? Or doing wrong?

Thanks!

**Comment by dami82** [comment]
hi there. thanks for using easyPubMed. As stated in the manual/help, the max batch size is 5000. Numbers bigger than 5000 are reset to 5000. All your results are dowloaded (possibly saved as multiple files), and each file stores up to 5000 records.

Best regards,
Damiano

——
Damiano Fantini

**Comment by dami82** [comment]
Also, this vignette could be useful: [https://www.data-pulse.com/projects/Rlibs/vignettes/easyPubMed_03_retmax_example.html](https://www.data-pulse.com/projects/Rlibs/vignettes/easyPubMed_03_retmax_example.html).

It covers the usage of `retstart` / `retmax`; make sure to parse all files downloaded via `batch_pubmed_download()`

**Comment by rempsyc** [comment]
I apologize in advance for commenting on a closed issue. I think the issue here is not a bug but the behaviour of `articles_to_list()` in conjunction with `batch_pubmed_download()`. I understand that `batch_pubmed_download()` downloads several batches (14 batches of size 5 in the example below).

I think your vignettes include no direct example of using `articles_to_list()` with `batch_pubmed_download()`, but I figured that it would be similar to your [example vignette](https://www.data-pulse.com/projects/Rlibs/vignettes/easyPubMed_01_getting_started.html), in which you use `articles_to_list()` by indexing, e.g.,

``` r
out.B <- batch_pubmed_download(pubmed_query_string = new_PM_query, dest_file_prefix = "apex1_sample")
# Retrieve the full name of the XML file downloaded in the previous step
new_PM_file <- out.B[1]
```

However, what is not documented is that using `articles_to_list()` on the resulting `d.fls` silently takes the first batch, so is identical to indexing with [1], instead of apply to all batches. Reprex below:

``` r
# Assuming the goal is to get a data frame of the data, then there seems to be several steps involved:

library(easyPubMed)

d.fls <- batch_pubmed_download(pubmed_query_string = "2019[yr] AND Basic and clinical neuroscience [Journal]", 
                               batch_size = 5)
#> [1] "PubMed data batch 1 / 14 downloaded..."
#> [1] "PubMed data batch 2 / 14 downloaded..."
#> [1] "PubMed data batch 3 / 14 downloaded..."
#> [1] "PubMed data batch 4 / 14 downloaded..."
#> [1] "PubMed data batch 5 / 14 downloaded..."
#> [1] "PubMed data batch 6 / 14 downloaded..."
#> [1] "PubMed data batch 7 / 14 downloaded..."
#> [1] "PubMed data batch 8 / 14 downloaded..."
#> [1] "PubMed data batch 9 / 14 downloaded..."
#> [1] "PubMed data batch 10 / 14 downloaded..."
#> [1] "PubMed data batch 11 / 14 downloaded..."
#> [1] "PubMed data batch 12 / 14 downloaded..."
#> [1] "PubMed data batch 13 / 14 downloaded..."
#> [1] "PubMed data batch 14 / 14 downloaded..."

list.articles <- articles_to_list (d.fls)

length(list.articles)
#> [1] 5

list.articles.df <- lapply(list.articles, article_to_df)

articles.df <- do.call(rbind, list.articles.df)

nrow(articles.df)
#> [1] 28
```

<sup>Created on 2023-05-28 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

I think it would be more intuitive if `articles_to_list()` would automatically apply to all batches without the need for indexing manually. Otherwise, there should be a message saying that only the first batch was selected and instructions on how to take extract the rest of the data.

**Comment by rempsyc** [comment]
Here is a function that provides the desired result directly.

``` r
library(easyPubMed)

d.fls <- batch_pubmed_download(pubmed_query_string = "2019[yr] AND Basic and clinical neuroscience [Journal]", 
                               batch_size = 5)
#> [1] "PubMed data batch 1 / 14 downloaded..."
#> [1] "PubMed data batch 2 / 14 downloaded..."
#> [1] "PubMed data batch 3 / 14 downloaded..."
#> [1] "PubMed data batch 4 / 14 downloaded..."
#> [1] "PubMed data batch 5 / 14 downloaded..."
#> [1] "PubMed data batch 6 / 14 downloaded..."
#> [1] "PubMed data batch 7 / 14 downloaded..."
#> [1] "PubMed data batch 8 / 14 downloaded..."
#> [1] "PubMed data batch 9 / 14 downloaded..."
#> [1] "PubMed data batch 10 / 14 downloaded..."
#> [1] "PubMed data batch 11 / 14 downloaded..."
#> [1] "PubMed data batch 12 / 14 downloaded..."
#> [1] "PubMed data batch 13 / 14 downloaded..."
#> [1] "PubMed data batch 14 / 14 downloaded..."

all_articles_to_list <- function(d.fls){
  y <- lapply(seq_along(d.fls), function(x) {
    list.articles <- articles_to_list(d.fls[x])
    list.articles.df <- lapply(list.articles, article_to_df)
    articles.df <- do.call(rbind, list.articles.df)
  })
  do.call(rbind, y)
}

my_data_frame <- all_articles_to_list(d.fls)

nrow(my_data_frame)
#> [1] 327
```

<sup>Created on 2023-05-28 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>


Would you be interested in me submitting a PR for this? Happy to make changes if you think it would be useful to anybody else but me.

**Comment by dami82** [comment]
Hi Remy. Thanks for the suggestion and for your code. Your point is well taken. I'll keep this in mind for future releases of `easyPubMed`. I like your suggestions and I think it would be best to enable the behavior you proposed in the `articles_to_list()` function and the `table_articles_byAuth()` function directly, without adding a dedicated new function. 
I sincerely thank you for your interest and your help, but please, don't submit a PR for this at this time. I have been doing some work offline to resolve some bugs due to the recent Entrez server updates, so I'd like to push those first. Please, be a little patient. Thanks.

**Comment by rempsyc** [comment]
Awesome! :) I'll wait patiently and don't hesitate to adapt the code above when you get to reworking those functions. Thanks for your work!

Also, thanks for pointing out the `table_articles_byAuth()` function. I have missed it somehow. I think when I saw it I assumed it was related to needing a special server Auth-entication or Auth-orization, but it was in fact arranging the data frame by Auth-or ;) Even reading the description and title, I did not make the link at first. Maybe this could be clearer (either in the docs or in the function name). Because I don't think it needs to mention by authors in the function name if this is the only function to convert the articles to a data frame (and the most logical outcome?). That said, I should have noticed caught up faster since it was well explained in the vignettes as well. Thanks again.
